---
title: "Untitled"
author: "David Langenohl"
date: "16 3 2021"
output: html_document
---

<style type="text/css">

body{ /* Normal  */
      font-size: 20px;
      font-family: "Times New Roman", Times, serif;
      color: Black;
  }
  
</style>

Looking at the pictures above, you can see three results compared to the RGB-picture on the far right (which is linear-stretched, as this leads to a better visibility of the *Fairy Rings*): *U-Net*, *SegOptim* with RGB-only, *SegOptim* with the 17-layer stack (including the *green* channel) + *blue* and *green* channels. The RGB-*SegOptim*-Model was trained for a more in-depth comparison to the *U-Net* model, as the *U-Net* algorithm did also just use the three RGB-layers. So, comparing those two models' results it is unambiguous that *U-Net* (far left) did an undisputedly better job than SegOptim (middle-left), when solely relying on the RGB-layers. On the other hand, comparing the *U-Net* result with those of the SegOptim trained with the large stack, it remains less clear. Looking at both images reveals, that *U-Net* delivered cleaner structures, whereas the SegOptim algorithm created a noisier image with a lot of small points, classified as *Fairy Ring*, which do not seem to really belong to a larger *Fairy Ring* structure. On the other hand, *U-Net* is missing some structures, that where classified as *Fairy Ring* by *SegOptim* and that seem to belong to a *Fairy Ring*, when comparing it to the RGB-image.

Looking into the models' accuracies, results in a strange picture at first:  
*SegOptim* with full stack: 0.8, *SegOptim* with RGB-stack: 0.85  
While it seems a bit odd in the first place, that the higher accuracy was achieved by *SegOptim* using the RGB stack, it gets clear when thinking of it in detail: the algorithm did predict only a few pixels as *Fairy Ring*, making it less likely to make False-Positive-mistakes here. More mistakes were made by False-Negative prediction, marking *Fairy Rings* as *non Fairy Ring*. But as, in the end, the *Fairy Rings* make up the smaller part of the picture, these mistakes do not have that much of an impact onto the accuracy.  

However, when taking the models' F1-values into consideration, which do not take into account the right prediction of *non Fairy Ring* oixels but only the right prediction of *Fairy Rings*, the result is relatively clear:
*U-Net*: 0.79, *SegOptim* with full stack: 0.50, *SegOptim* with RGB-stack: 0.38  
*U-Net* turns out to be way better in predicting the presence of *Fairy Ring* in the given section. This assumption is stressed by having a look onto the validation raster to the right: *SegOptim* is likely to have benefited from the area we chose for validation. Here, it did a pretty good job. But having a look onto other areas like the one in the lower left corner of the RGB-image, one might get the idea that *SegOptim* did not perform that well here, as it predicted a lot of *Fairy Ring* although, by looking at it with the help of the **God's view method** (<a href="https://www.uni-marburg.de/de/fb19/fachbereich/staff/dr-christoph-reudenbauch" target="_blank">Dr. Christoph Reudenbach</a>), it can occur to one that there aren't that many *Fairy Rings*. Instead, the strange colorization at that corner is likely to be attributed to a cloud, blocking the sunlight during the recording of the image.

So, taking everything into consideration, which one do we believe to be the better method for predicting *Fairy Rings* in an area like our *spanish mountain meadow*? Well, as so often, this mainly depends on your data, your usecase and your computational ressources. If your aim is to detect any possible presence of a *Fairy Ring* on a given area and you don't mind the algorithm being time-consuming and hardware-intensive, then you might be pleased with *SegOptim*. On the other hand, when you prefer the method being (slightly) faster and do not want to put much effort or thought into the layers you need to feed the algorithm, *U-Net* might be the better option. Also, *U-Net* provided the 'prettier' result, as the *Fairy Rings* were sharper and more clearly differentiated from the surroundings. However, it was a little less accurate and might have overlooked some *Fairy Rings* or parts of those.  
As you can see from the results and as I mentioned in the beginning, detecting *Fairy Rings* computationally is not an easy task, even though it might seem quite simple based on how easy it is for us to detect them on a picture. In the end, what the great Dumbeldore said to Harry holds true: *Don’t count your owls before they are delivered.*


