---
title: "desc_test"
author: "David Langenohl"
date: "15 3 2021"
output: html_document
---

<style type="text/css">

body{ /* Normal  */
      font-size: 20px;
      font-family: "Times New Roman", Times, serif;
      color: Black;
  }
  
</style>

*Fairy Rings*, despite their magical names, are not subject of any high fantasy novel taking place in a mystical place. On the contrary, they are just a rather interesting real world phenomenon that inspired numerous folklore including witches, dragons and, obviously, fairies. The (lower) image on the left represents what a *Fairy Ring* looks like in reality: it's a ring of mushrooms. Beeing found mainly in forested areas, but also appearing in grass- or rangelands, those rings can grow to more than 10m in diameter. Though the reasons for their circular appearance and their genesis are certainly interesting, they are not subject of this project. The very curious minds, mycology maniacs and fungus fanatics are welcome to follow <a href="https://en.wikipedia.org/wiki/Fairy_ring" target="_blank">this link to Wikipedia</a> and learn more about *Fairy Rings* and the strange stuff people made up for them over the centuries. In the meantime, I will progress with the real subject of this project: using machine learning to automatically detect *Fairy Rings* in grasslands. "Well, sounds pretty easy! Even my grandma would find those toadstool toruses on a field!", you might think. After wondering why anyone would use the word "torus" instead of "ring" and assuring you, that those novel computers will never repalce your grandmother, I would proceed with explaining you that a computer is lacking some essential skills that help your grandmother to distinguish between "meadow" and "mushroom ring": experience ("I know what grassland looks like") combined with seeing multiple interrelations at once ("This is a circular shape, which looks strange, **AND** it has another color that the surrounding meadow") for example, just to name a few. So, you see, letting a PC automatically detect certain structures is not an easy task, even if it seems easy from a human perspective.
Bulding upon this, the idea behind this project is to present two different machine learning approaches in predicting *Fairy Rings*:

1. U-Net - a convolutional neural network
2. SegOptim - object-based image classification

On the next few pages we will lead you through the process of model training, prediction and validation and will present you the results. But first, let's start with the area of interest, where we want to detect our *Fairy Rings*.